<?php

/**
 * Implements hook_views_api().
 */
function views_summarize_views_api() {
  return array(
    'api' => 3,
  );
}


/*
 * Implements hook_theme().
 */
function views_summarize_theme() {
  return array(
    'views_summarize_plugin_style_tablesummarized' => array(
      'render element' => 'form',
    ),
    'views_summarize_type_none' => array(
      'variables' => array('data' => array()),
    ),
    'views_summarize_type_count' => array(
      'variables' => array('data' => array()),
    ),
    'views_summarize_type_unique' => array(
      'variables' => array('data' => array()),
    ),
    'views_summarize_type_range' => array(
      'variables' => array('data' => array()),
    ),
    'views_summarize_type_spread' => array(
      'variables' => array('data' => array()),
    ),
    'views_summarize_type_total' => array(
      'variables' => array('data' => array()),
    ),
    'views_summarize_type_average' => array(
      'variables' => array('data' => array()),
    ),
    'views_summarize_type_average_no_empties' => array(
      'variables' => array('data' => array()),
    ),
  );
}


/**
 * Returns a list of the available handlers.
 *
 * @return array
 *   The handlers.
 */
function views_summarize_get_handlers() {
  static $handlers = NULL;
  if (!isset($handlers)) {
    $handlers = module_invoke_all('views_summarize_handlers');
  }
  return $handlers;
}

/**
 * Implements hook_views_summarize_handlers().
 */
function views_summarize_views_summarize_handlers() {
  return array(
    'views_summarize_type_none'               => t('None'),
    'views_summarize_type_count'              => t('Count'),
    'views_summarize_type_unique'             => t('Unique'),
    'views_summarize_type_range'              => t('Range'),
    'views_summarize_type_total'              => t('Total'),
    'views_summarize_type_average'            => t('Average (include empty values)'),
    'views_summarize_type_average_no_empties' => t('Average (exclude empty values)'),
    'views_summarize_type_spread'             => t('Spread'),
  );
}


/**
 * Displays a view as a table summary.
 */
function template_preprocess_views_summarize_views_tablesummarized(&$vars) {
  template_preprocess_views_view_table($vars);

  if (!count($vars['rows'])) {
    return;
  }

  $opts =& $vars['view']->style_plugin->options['info'];

  if (isset($vars['view']->style_plugin->options['summary_only'])) {
    $vars['summary_only'] = $vars['view']->style_plugin->options['summary_only'];
  }
  if (isset($vars['view']->style_plugin->options['summary_above'])) {
    $vars['summary_above'] = $vars['view']->style_plugin->options['summary_above'];
  }
  if (isset($vars['view']->style_plugin->options['summary_below'])) {
    $vars['summary_below'] = $vars['view']->style_plugin->options['summary_below'];
  }

  $data = array();
  foreach ($vars['rows'] as $row) {
    foreach ($row as $field => $value) {
      $data[$field]['values'][] = $value;
    }
  }

  $vars['summarized'] = array();
  foreach ($opts as $field => $settings) {
    if (isset($data[$field])) {
      // Get the display's field settings.
      $field_settings = array();
      if (!empty($vars['view']->field[$field]->options['settings'])) {
        $field_settings = $vars['view']->field[$field]->options['settings'];
      }

      // Get the field instance settings.
      $field_config_settings = array();
      if (!empty($vars['view']->style_options['info'][$field])) {
        $field_config_settings = $vars['view']->style_options['info'][$field];
      }

      $data[$field]['options'] = array(
        'field' => $field,
        'views_field_settings' => $field_settings,
        'field_instance_settings' => $field_config_settings,
      );
      $vars['summarized'][$field] = theme($settings['summarize'], $data[$field]);
    }
  }
}


/**
 * Themes the form for the display style plugin.
 *
 * This is almost the same as theme_views_ui_style_plugin_table().
 */
function theme_views_summarize_plugin_style_tablesummarized($variables) {
  $form = $variables['form'];

  $output = drupal_render($form['description_markup']);

  $header = array(
    t('Field'),
    t('Column'),
    t('Align'),
    t('Separator'),
    t('Summarize prefix'),
    t('Summarize'),
    t('Summarize suffix'),
    t('Summarize thousand'),
    t('Summarize decimal'),
    t('Summarize precision'),
    array(
      'data' => t('Sortable'),
      'align' => 'center',
    ),
    array(
      'data' => t('Default order'),
      'align' => 'center',
    ),
    array(
      'data' => t('Default sort'),
      'align' => 'center',
    ),
    array(
      'data' => t('Hide empty column'),
      'align' => 'center',
    ),
  );
  $rows = array();
  foreach (element_children($form['columns']) as $id) {
    $row = array();
    $row[] = drupal_render($form['info'][$id]['name']);
    $row[] = drupal_render($form['columns'][$id]);
    $row[] = drupal_render($form['info'][$id]['align']);
    $row[] = drupal_render($form['info'][$id]['separator']);
    $row[] = drupal_render($form['info'][$id]['prefix']);
    $row[] = drupal_render($form['info'][$id]['summarize']);
    $row[] = drupal_render($form['info'][$id]['suffix']);
    $row[] = drupal_render($form['info'][$id]['thousand']);
    $row[] = drupal_render($form['info'][$id]['decimal']);
    $row[] = drupal_render($form['info'][$id]['precision']);
    if (!empty($form['info'][$id]['sortable'])) {
      $row[] = array(
        'data' => drupal_render($form['info'][$id]['sortable']),
        'align' => 'center',
      );
      $row[] = array(
        'data' => drupal_render($form['info'][$id]['default_sort_order']),
        'align' => 'center',
      );
      $row[] = array(
        'data' => drupal_render($form['default'][$id]),
        'align' => 'center',
      );
    }
    else {
      $row[] = '';
      $row[] = '';
      $row[] = '';
    }
    $row[] = array(
      'data' => drupal_render($form['info'][$id]['empty_column']),
      'align' => 'center',
    );
    $rows[] = $row;
  }

  // Add the special 'None' row.
  $rows[] = array(t('None'), '', '', '', '', '', '', '', '', '', '', '', array('align' => 'center', 'data' => drupal_render($form['default'][-1])), '');

  $output .= theme('table', array('header' => $header, 'rows' => $rows));
  $output .= drupal_render_children($form);
  return $output;
}

/**
 * Themes a no summary for the column.
 */
function theme_views_summarize_type_none($variables) {
  return '';
}


/**
 * Themes the number of non-empty values in the column.
 */
function theme_views_summarize_type_count($variables) {
  $values = $variables['values'];
  $options = $variables['options'];

  if (!empty($values) && is_array($values)) {
    foreach ($values as $value) {
      $values2[] = strip_tags($value);
    }
  }

  $result = count(array_filter($values2, '_views_summarize_type_count_filter'));

  $summary = _views_summarize_get_summary_output($result, $options);
  return theme('table', array(
    'header' => array(array('data' => t('Count'))),
    'rows'   => array(array($summary)),
  ));
}

/**
 * Checks whether the given value is set (i.e., not null) or not.
 *
 * @param int $value
 *   The value to check.
 */
function _views_summarize_type_count_filter($value) {
  return isset($value);
}

/**
 * Themes the number of unique, non-empty values in the column.
 */
function theme_views_summarize_type_unique($variables) {
  $values = $variables['values'];
  $options = $variables['options'];

  if (!empty($values) && is_array($values)) {
    foreach ($values as $value) {
      $values2[] = strip_tags($value);
    }
  }

  $result = count(array_unique(array_filter($values2)));

  $summary = _views_summarize_get_summary_output($result, $options);
  return theme('table', array(
    'header' => array(array('data' => t('Unique'))),
    'rows'   => array(array($summary)),
  ));
}

/**
 * Themes the minimum and maximum values in the column.
 */
function theme_views_summarize_type_range($variables) {
  $values = $variables['values'];
  $options = $variables['options'];
  $header = array(
    array(
      'data' => t('Range'),
      'colspan' => 2,
    ),
  );

  if (!empty($values) && is_array($values)) {
    foreach ($values as $value) {
      $values2[] = floatval(_views_summarize_get_cleaned_value($value, $options));
    }
  }

  $min = _views_summarize_get_formatted_summary(min($values2), $options);
  $max = _views_summarize_get_formatted_summary(max($values2), $options);

  $min = _views_summarize_get_summary_output($min, $options);
  $max = _views_summarize_get_summary_output($max, $options);

  return theme('table', array(
    'header' => $header,
    'rows'   => array(
      array(
        t('Min'),
        $min,
      ),
      array(
        t('Max'),
        $max,
      ),
    ),
  ));
}

/**
 * Themes the total value for the values in the column.
 */
function theme_views_summarize_type_total($variables) {
  $values = $variables['values'];
  $options = $variables['options'];
  $total = 0;

  if (!empty($values) && is_array($values)) {
    foreach ($values as $value) {
      $total += floatval(_views_summarize_get_cleaned_value($value, $options));
    }
  }

  // Get the total, taking into account any display style settings.
  $result = _views_summarize_get_formatted_summary($total, $options);

  $summary = _views_summarize_get_summary_output($result, $options);
  return theme('table', array(
    'header' => array(array('data' => t('Total'))),
    'rows'   => array(array($summary)),
  ));
}


/**
 * Themes the average of the values in the column w/empty data values included.
 */
function theme_views_summarize_type_average($variables) {
  $values = $variables['values'];
  $options = $variables['options'];
  $total = 0;

  if (!empty($values) && is_array($values)) {
    foreach ($values as $value) {
      $total += floatval(_views_summarize_get_cleaned_value($value, $options));
    }
  }

  // Get the average, taking into account any display style settings.
  $result = _views_summarize_get_formatted_summary($total / count($values), $options);

  $summary = _views_summarize_get_summary_output($result, $options);
  return theme('table', array(
    'header' => array(array('data' => t('Average (including empty values)'))),
    'rows'   => array(array($summary)),
  ));
}


/**
 * Themes the average of the values in the column w/empty data values excluded.
 */
function theme_views_summarize_type_average_no_empties($variables) {
  $values = $variables['values'];
  $options = $variables['options'];
  $total = 0;
  $count = 0;

  if (!empty($values) && is_array($values)) {
    foreach ($values as $value) {
      if (isset($value) && $value != '') {
        $total += floatval(_views_summarize_get_cleaned_value($value, $options));
        $count++;
      }
    }
  }

  // Get the average, taking into account any display style settings.
  if ($total != 0 && $count != 0) {
    $result = _views_summarize_get_formatted_summary($total / $count, $options);
  }
  else {
    $result = 0;
  }

  $summary = _views_summarize_get_summary_output($result, $options);
  return theme('table', array(
    'header' => array(array('data' => t('Average (excluding empty values)'))),
    'rows'   => array(array($summary)),
  ));
}


/**
 * Themes a spread table for the values in the column.
 */
function theme_views_summarize_type_spread($variables) {
  $values = $variables['values'];
  $hist = array();
  $header = array(
    array(
      'data' => t('Spread'),
      'colspan' => 2,
    ),
  );
  $rows = array();

  if (!empty($values) && is_array($values)) {
    foreach ($values as $val) {
      if (!isset($hist[$val])) {
        $hist[$val] = 0;
      }
      $hist[$val]++;
    }

    foreach ($hist as $value => $count) {
      if (empty($value)) {
        $empty_string = t('(empty)');
        $rows[$empty_string] = array($empty_string, $count);
      }
      else {
       $value = strip_tags($value);
       $rows[$value] = array($value, $count);
      }
    }

    if (version_compare(phpversion(), '5.4.0', '>=')) {
      ksort($rows, SORT_NATURAL);
    }
    else {
      ksort($rows);
    }
  }

  return theme('table', array(
    'header' => $header,
    'rows'   => $rows,
  ));
}

/**
 * Gets the record's value after stripping invalid characters.
 *
 * @param type $value
 *   The value from which to strip invalid characters.
 * @param type $options
 *   The options element of the variables array that is passed into the summary
 *   theme function.
 *
 * @return array
 *  The value with invalid characters removed.
 */
function _views_summarize_get_cleaned_value($value, $options) {
  $value = preg_replace('/[^0-9\.\,\-]/', '', strip_tags($value));

  if (!empty($options['views_field_settings']['thousand_separator'])) {
    $value = str_replace($options['views_field_settings']['thousand_separator'], '', $value);
  }
  if (!empty($options['views_field_settings']['decimal_separator'])) {
    $value = str_replace($options['views_field_settings']['decimal_separator'], '.', $value);
  }

  return $value;
}

/**
 * Gets the summary's formatted result.
 *
 * @param type $total
 *   The summary to format.
 * @param type $options
 *   The options element of the variables array that is passed into the summary
 *   theme function.
 *
 * @return array
 *   The format settings in an associative array.
 */
function _views_summarize_get_formatted_summary($total, $options) {
  $format_settings = array(
    'precision' => 0,
    'decimal_separator' => NULL,
    'thousand_separator' => NULL,
  );

  if (!empty($options['field_instance_settings']['precision'])) {
    $format_settings['precision'] = (int) $options['field_instance_settings']['precision'];
  }
  if (!empty($options['field_instance_settings']['decimal'])) {
    $format_settings['decimal_separator'] = $options['field_instance_settings']['decimal'];
  }
  if (!empty($options['field_instance_settings']['thousand'])) {
    $format_settings['thousand_separator'] = $options['field_instance_settings']['thousand'];
  }

  $summary = number_format(
    $total,
    $format_settings['precision'],
    $format_settings['decimal_separator'],
    $format_settings['thousand_separator']
  );

  return $summary;
}

/**
 * Gets the prefix and suffix for a summary's output, if they exist.
 *
 * @param array $result
 *   The calculated summary.
 * @param array $options
 *   The options element of the variables array that is passed into the summary
 *   theme function.
 *
 * @return array
 *   The prefix and suffix in an associative array.
 */
function _views_summarize_get_summary_output($result, $options) {
  $prefix_suffix = array(
    'prefix' => '',
    'suffix' => '',
  );

  if (!empty($options['field_instance_settings']['prefix'])) {
    $prefix_suffix['prefix'] = $options['field_instance_settings']['prefix'];
  }
  if (!empty($options['field_instance_settings']['suffix'])) {
    $prefix_suffix['suffix'] = $options['field_instance_settings']['suffix'];
  }

  return $prefix_suffix['prefix'] . $result . $prefix_suffix['suffix'];
}
