<?php

/**
 * @file
 * Provides a views display that outputs summaries of the values in a table.
 */

module_load_include('inc', 'views_summarize', 'views/views_summarize.views');

/**
 * Implements hook_autoload_info().
 */
function views_summarize_autoload_info() {
  return array(
    'views_summarize_plugin_style_tablesummarized' => 'views/views_summarize_plugin_style_tablesummarized.inc',
  );
}

/**
 * Implements hook_views_api().
 */
function views_summarize_views_api() {
  return array(
    'api' => 3.0,
  );
}

/**
 * Implements hook_theme().
 */
function views_summarize_theme() {
  $default = array(
    'variables' => array(
      'data' => array(),
    ),
    'file' => 'templates/views_summarize.theme.inc',
  );
  return array(
    'views_summarize_plugin_style_tablesummarized' => array(
      'render element' => 'form',
      'file' => 'templates/views_summarize.theme.inc',
    ),
    'views_summarize_type_none' => $default,
    'views_summarize_type_count' => $default,
    'views_summarize_type_unique' => $default,
    'views_summarize_type_range' => $default,
    'views_summarize_type_spread' => $default,
    'views_summarize_type_total' => $default,
    'views_summarize_type_average' => $default,
  );
}

/**
 * Returns a list of the available handlers.
 *
 * @return array
 *   The handlers.
 */
function views_summarize_get_handlers() {
  static $handlers = NULL;
  if (!isset($handlers)) {
    $handlers = module_invoke_all('views_summarize_handlers');
  }
  return $handlers;
}

/**
 * Implements hook_views_summarize_handlers().
 */
function views_summarize_views_summarize_handlers() {
  return array(
    'views_summarize_type_none' => t('None'),
    'views_summarize_type_count' => t('Count'),
    'views_summarize_type_unique' => t('Unique'),
    'views_summarize_type_range' => t('Range'),
    'views_summarize_type_total' => t('Total'),
    'views_summarize_type_average' => t('Average'),
    'views_summarize_type_spread' => t('Spread'),
  );
}
